I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 211, in script call
    call basilAndDaisy from _call_basilAndDaisy
  File "game/script.rpy", line 553, in script
    g "And I promised my parents that when I had a kid, I would support them 100% with making their own decisions."
ValueError: unsupported format character 'w' (0x77) at index 75

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 211, in script call
    call basilAndDaisy from _call_basilAndDaisy
  File "game/script.rpy", line 553, in script
    g "And I promised my parents that when I had a kid, I would support them 100% with making their own decisions."
  File "/Applications/renpy-8.0.3-sdk/renpy/ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-8.0.3-sdk/renpy/exports.py", line 1362, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character 'w' (0x77) at index 75

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
ikebunny 1.0
Tue Apr 11 15:12:39 2023
